---
title: "Untitled"
output: html_document
---


```{r, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, warning = FALSE)
library(flowCore)
library(CATALYST)
library(umap)
library(R.utils)
```

# Input data

Input the data from design file into a SingleCellExperiment class object using the wrapper function prepData from CATALYST. 

```{r input}
# design_<dir>_<sample>.csv
design_files <- list.files(pattern = "design_")

for (i in design_files){
  x <- strsplit(i, "_")
  dir_files <- x[[1]][2]
  dir_files <- paste0("input/", dir_files)
  dir.create(file.path("input"), showWarnings = FALSE)
  dir.create(file.path(dir_files), showWarnings = FALSE)
  
  md <- read.csv(i)

  file_names <- as.vector(md$file_name)
  linked_files <- gsub("./","", file_names)
  linked_files <- paste0(getwd(), "/" ,linked_files)
  
  
  output_dir <- paste0(getwd(), "/", dir_files, "/")
  
  
  for (y in linked_files){
    file.symlink(y, output_dir)
  } 
  
  
  fcs_files <- list.files(path = output_dir, pattern = ".fcs$", full.names = T)
  md$file_name <- fcs_files
  fs <- read.flowSet(fcs_files, transformation = FALSE, truncate_max_range = FALSE)
  
  
  panel <- read.csv("metals_meta_expressed.csv", stringsAsFactors = T)

  md$condition <- factor(md$condition, levels = "amo")
  md$sample_id <- factor(md$sample_id, levels = md$sample_id[order(md$condition)])
  
  sce <- prepData(fs, panel, md)
  
  assign(paste("sce", i, sep = "."), sce)
}
```

# Plot expression

```{r expression}


p <- plotExprs(daf, color_by="patient_id")
p$facet$params$ncol <- 6
#png("plotExprs.png", width = 1400, height = 1400)
#p
#dev.off()
p
```

# Plot counts

```{r counts}
#png("plotCounts.png")
#plotCounts(daf, color_by = "condition")
#dev.off()
plotCounts(daf, color_by = "patient_id")
```


# Heatmap

```{r heatmap}
plotExprHeatmap(daf, color_by="patient_id", draw_freqs=FALSE)
```

# Clustering 

```{r}

daf <- cluster(daf, cols_to_use=colnames(daf), xdim = 10, ydim = 10 ,maxK =20, seed = 1234)

plotClusterHeatmap(daf, hm2= NULL, k = "meta12", m = NULL, draw_freqs = TRUE)

```

# UMAP

```{r}

daf <- runDR(daf, "TSNE", rows_to_use=1000, overwrite = TRUE)
daf <- runDR(daf, "UMAP", rows_to_use=1000, overwrite = TRUE)

plotDR(daf, "TSNE", color_by = "meta12")
```


# TSNE condition

```{r}
plotDR(daf, "TSNE", color_by = "CD38", facet= "patient_id")
```

# TSNE 

```{r}
plotDR(daf, "TSNE", color_by = "meta12", facet= "patient_id")
```

```{r}
plotDR(daf, "TSNE", color_by = "Ki67", facet= "patient_id")
```